spring.application.name=TaskboardBackend

spring.datasource.url=jdbc:postgresql://localhost:5432/taskboard
spring.datasource.username=${DB_USERNAME:taskboard}
spring.datasource.password=${DB_PASSWORD:taskboard}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
